# Generated by Django 5.1.4 on 2025-01-31 00:37

import blog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
            ],
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="carousel",
            options={"verbose_name": "Carousel", "verbose_name_plural": "Carousels"},
        ),
        migrations.AlterModelOptions(
            name="carouselimage",
            options={
                "verbose_name": "Carousel Image",
                "verbose_name_plural": "Carousel Images",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="restrictedpage",
            options={
                "verbose_name": "Restricted Page",
                "verbose_name_plural": "Restricted Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="zoomevent",
            options={
                "verbose_name": "Zoom Event",
                "verbose_name_plural": "Zoom Events",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Biography",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="email_address",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="authors",
                validators=[blog.models.validate_image_size],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="description",
            field=models.TextField(
                blank=True, max_length=400, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="caption",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Caption"
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="carousel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blog.carousel",
                verbose_name="Carousel",
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="image",
            field=models.ImageField(
                upload_to="carousel/images",
                validators=[blog.models.validate_image_size],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=400, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_email",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=100, verbose_name="User Name"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(max_length=400, verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=100, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="post",
            name="access_type",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
                verbose_name="Access Type",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=200, null=True, verbose_name="Excerpt"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts", to="blog.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="youtube_url",
            field=models.URLField(null=True, verbose_name="YouTube URL"),
        ),
        migrations.AlterField(
            model_name="restrictedpage",
            name="access_code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Access Code"
            ),
        ),
        migrations.AlterField(
            model_name="restrictedpage",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="restrictedpage",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="caption",
            field=models.CharField(max_length=20, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="access_type",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
                verbose_name="Access Type",
            ),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="event_time",
            field=models.DateTimeField(verbose_name="Event Time"),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="type",
            field=models.CharField(
                choices=[("webinar", "Webinar"), ("workshop", "Workshop")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="zoomevent",
            name="zoom_link",
            field=models.URLField(verbose_name="Zoom Link"),
        ),
    ]
