# Generated by Django 5.1.4 on 2025-02-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_product_alter_author_options_alter_carousel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(max_length=400, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_es",
            field=models.TextField(max_length=400, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ka",
            field=models.TextField(max_length=400, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ka",
            field=models.CharField(max_length=100, null=True, verbose_name="Question"),
        ),
    ]
