# Generated by Django 5.1.4 on 2025-02-01 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_faq_answer_en_faq_answer_es_faq_answer_ka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="bio_en",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Biography",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="bio_es",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Biography",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="bio_ka",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Biography",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="first_name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="first_name_es",
            field=models.CharField(
                max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="first_name_ka",
            field=models.CharField(
                max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="last_name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Last Name"),
        ),
        migrations.AddField(
            model_name="author",
            name="last_name_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Last Name"),
        ),
        migrations.AddField(
            model_name="author",
            name="last_name_ka",
            field=models.CharField(max_length=100, null=True, verbose_name="Last Name"),
        ),
    ]
