# Generated by Django 5.1.4 on 2025-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_webproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="description_es",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="description_ka",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="name_es",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="name_ka",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Product Name"
            ),
        ),
    ]
