# Generated by Django 5.1.4 on 2025-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_faq_main"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="bio_ka",
        ),
        migrations.RemoveField(
            model_name="author",
            name="first_name_ka",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name_ka",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_ka",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_ka",
        ),
        migrations.RemoveField(
            model_name="webproduct",
            name="description_ka",
        ),
        migrations.RemoveField(
            model_name="webproduct",
            name="name_ka",
        ),
    ]
