# Generated by Django 5.1.4 on 2025-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total budget allocated for the project.",
                max_digits=10,
                verbose_name="Budget",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total cost incurred so far (optional).",
                max_digits=10,
                null=True,
                verbose_name="Cost",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer_email",
            field=models.EmailField(
                help_text="Customer's email address.",
                max_length=254,
                verbose_name="Customer Email",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer_name",
            field=models.CharField(
                help_text="Name of the customer.",
                max_length=255,
                verbose_name="Customer Name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Customer's phone number.",
                max_length=20,
                null=True,
                verbose_name="Customer Phone",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the project.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="The estimated or actual completion date of the project.",
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image related to the project.",
                null=True,
                upload_to="project_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Project Name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the project.",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_video",
            field=models.URLField(
                blank=True,
                help_text="Link to a video of the project (optional).",
                null=True,
                verbose_name="Project Video",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                help_text="The date the project started.", verbose_name="Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="planning",
                help_text="Current status of the project.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
