# Generated by Django 5.1.4 on 2025-02-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_options_alter_project_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(
                help_text="Detailed description of the project.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_es",
            field=models.TextField(
                help_text="Detailed description of the project.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ka",
            field=models.TextField(
                help_text="Detailed description of the project.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Project Name"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="name_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Project Name"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="name_ka",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Project Name"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notes_en",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the project.",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notes_es",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the project.",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notes_ka",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the project.",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="planning",
                help_text="Current status of the project.",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status_es",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="planning",
                help_text="Current status of the project.",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status_ka",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="planning",
                help_text="Current status of the project.",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
