# Generated by Django 5.1.4 on 2025-02-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_description_en_project_description_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="notes_en",
        ),
        migrations.RemoveField(
            model_name="project",
            name="notes_es",
        ),
        migrations.RemoveField(
            model_name="project",
            name="notes_ka",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status_en",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status_es",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status_ka",
        ),
    ]
