# Generated by Django 5.1.4 on 2025-02-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_range_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Price Range"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_range_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Price Range"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_range_ka",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Price Range"
            ),
        ),
    ]
