# Generated by Django 5.1.4 on 2025-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_service_price_range_en_service_price_range_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description_ka",
        ),
        migrations.RemoveField(
            model_name="project",
            name="name_ka",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description_ka",
        ),
        migrations.RemoveField(
            model_name="service",
            name="features_ka",
        ),
        migrations.RemoveField(
            model_name="service",
            name="ideal_for_ka",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_range_ka",
        ),
        migrations.RemoveField(
            model_name="service",
            name="title_ka",
        ),
    ]
